<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address_Relative_adress-297</name>
   <tag></tag>
   <elementGuidId>7a17ac1e-d638-4724-b679-26d14c53d949</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Relative_adress-297</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Relative_adress-297']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>05ae6f02-8e52-48bb-bb1f-2f3c101a6d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2d02b831-b93a-41fc-bdb2-a36ed63fb41b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>um-form-field valid </value>
      <webElementGuid>f619b0c3-38a0-4875-9144-22379f37a114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>253e9107-fe52-45c8-a487-89141357ff4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Relative_adress-297</value>
      <webElementGuid>f588ea11-b00d-43a4-bdd3-da4ace8f1ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Relative_adress-297</value>
      <webElementGuid>589033a9-79c3-4471-99f9-22457a414eb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>Relative_adress</value>
      <webElementGuid>1935a604-67e6-4c04-8c5a-bd929da21285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Relative_adress-297&quot;)</value>
      <webElementGuid>b62876e8-92cc-4916-b450-83d2578977d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Relative_adress-297']</value>
      <webElementGuid>606035c0-c52c-4bd0-b4ad-758eda234f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='um_field_297_Relative_adress']/div[2]/input</value>
      <webElementGuid>5a938073-5e51-4cc8-b840-347bb77d9e91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/input</value>
      <webElementGuid>0965a41a-0a2f-4726-b4d6-3ab1dac0f20d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Relative_adress-297' and @id = 'Relative_adress-297']</value>
      <webElementGuid>0d59b331-ee24-48bd-b014-057686dbfb67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
