<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Keep me signed in_um-submit-btn</name>
   <tag></tag>
   <elementGuidId>edc46d15-79ea-43ad-a611-9f2146218b05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#um-submit-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='um-submit-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f95d3d44-36b4-4646-8668-01756f654ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c3e655b0-2fee-4013-a5d6-7417b177c116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>6ba69d76-f5e1-43fe-ac9d-4876d3e5f81c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>um-button</value>
      <webElementGuid>6bf02a1b-216e-46b8-a904-1b8782261319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>um-submit-btn</value>
      <webElementGuid>d982c6e8-a4dd-4b87-b6c0-2207af4f04cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;um-submit-btn&quot;)</value>
      <webElementGuid>f91c674c-4d3b-4b69-a0ff-68055192350f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='um-submit-btn']</value>
      <webElementGuid>0934598a-b7aa-4d9f-b0b6-b7ef4fda6dd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-313']/div/div/div/form/div[2]/div[3]/input</value>
      <webElementGuid>10811870-ee11-4132-81f7-b1f8e2ed0b37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>8983ec24-e5da-4e37-9d01-c49293221a59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'um-submit-btn']</value>
      <webElementGuid>8bdcbeb6-89e5-4b26-a53a-db4eb7515c71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
