<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__wpformsfields1</name>
   <tag></tag>
   <elementGuidId>2d534efb-0f51-4b9b-b173-952806f2bfff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wpforms-291-field_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wpforms-291-field_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7c62b20-45bb-4c5f-a4c3-26fc1e4411a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>37e783d1-003f-43cf-b7da-b8585f4d68cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wpforms-291-field_1</value>
      <webElementGuid>98467f69-b354-4e21-a185-41adb3c7c411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpforms-field-medium wpforms-field-required</value>
      <webElementGuid>2269f489-d58f-4c27-8e34-fb3295a5526c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wpforms[fields][1]</value>
      <webElementGuid>b9540a3e-585e-4692-a527-1fd0332f9e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpforms-291-field_1&quot;)</value>
      <webElementGuid>57b14225-65c2-4a5c-a5f0-d7c0a97fac22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8a9262c9-4983-4d2a-8e5b-87d585cf5284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>f71fe9c3-35c0-4867-b667-5f37ff192435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wpforms-291-field_1</value>
      <webElementGuid>c0cc89ec-9956-45b6-9112-45861608c9af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpforms-field-medium wpforms-field-required</value>
      <webElementGuid>11efaf72-2961-48b1-817d-5e874791a0c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wpforms[fields][1]</value>
      <webElementGuid>c6b36c3d-a2e8-40b2-8b1e-fe3dac8214a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpforms-291-field_1&quot;)</value>
      <webElementGuid>dcd2d898-d741-43e1-9e10-bb779b06415a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wpforms-291-field_1']</value>
      <webElementGuid>091f77f3-fc6d-4448-82be-0defc5ca19ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpforms-291-field_1-container']/input</value>
      <webElementGuid>9e95db06-3722-433c-95e0-7503f141c3f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>4411a5bd-131b-4fff-ad01-e493d660ceb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'wpforms-291-field_1' and @name = 'wpforms[fields][1]']</value>
      <webElementGuid>f3b90931-1249-4e22-95c8-d713efed2ed7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
